extends: ../../../config/afterSRC_compact.yaml
doc_name: CompactOne_afterSRC_access_ICF305

deployment:
  selected_chamber_candidate: aftersrc_square_icf305_access
  maintenance_access:
    selected_candidate: ICF305
