extends: ../../../config/afterSRC_compact.yaml
doc_name: CompactOne_afterSRC_access_ICF356

deployment:
  selected_chamber_candidate: aftersrc_square_icf356_access
  maintenance_access:
    selected_candidate: ICF356
