#!/usr/bin/env bash
set -euo pipefail

command -v git-lfs >/dev/null 2>&1 || {
  printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook or disable hooksPath."
  exit 2
}
git lfs post-commit "$@"
